// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var fs, gui, node, path, storage_dir, win;
    node = false;
    try {
      gui = require('nw.gui');
      fs = require('fs');
      path = require('path');
      win = gui.Window.get();
      win.show();
      win.showDevTools();
      $('#close').click(function() {
        return win.close();
      });
      $('#minimize').click(function() {
        return win.minimize();
      });
      $('#maximize').click(function() {
        return win.maximize();
      });
      $('#panel').mouseenter(function() {
        return $('#panel').addClass('drag');
      });
      $('#panel #decor img, #panel #noteControls img, #panel #search').mouseenter(function() {
        return $('#panel').removeClass('drag');
      });
      $('#panel #decor img, #panel #noteControls img, #panel #search').mouseleave(function() {
        return $('#panel').addClass('drag');
      });
      $('#panel').mouseleave(function() {
        return $('#panel').removeClass('drag');
      });
      node = true;
      storage_dir = process.env.HOME;
    } catch (e) {
      console.log("We're not running under node-webkit.");
    }
    $("#content header .edit").click(function() {
      if ($(this).text() === "save") {
        $(this).text("edit");
        return window.noted.editor.preview();
      } else {
        $(this).text("save");
        return window.noted.editor.edit();
      }
    });
    window.noted.editor = new EpicEditor({
      container: 'contentbody',
      theme: {
        base: '/themes/base/epiceditor.css',
        preview: '/themes/preview/style.css',
        editor: '/themes/editor/style.css'
      }
    });
    window.noted.editor.load();
    if (node) {
      return fs.readFile(path.join(storage_dir, 'file.txt'), 'utf-8', function(err, data) {
        if (err) {
          throw err;
        }
        window.noted.editor.importFile('file', data);
        return window.noted.editor.preview();
      });
    } else {
      window.noted.editor.importFile('file', "Not running under node webkit");
      return window.noted.editor.preview();
    }
  });

  window.noted = {};

}).call(this);
