// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $("#content header .edit").click(function() {
      if ($(this).text() === "save") {
        $(this).text("edit");
        return window.noted.preview();
      } else {
        $(this).text("save");
        return window.noted.edit();
      }
    });
    window.noted.editor = new EpicEditor({
      container: 'contentbody',
      theme: {
        base: '/themes/base/epiceditor.css',
        preview: '/themes/preview/style.css',
        editor: '/themes/editor/github.css'
      }
    });
    window.noted.editor.load();
    window.noted.editor.importFile('some-file', "#Imported markdown\nFancy, huh?");
    return window.noted.editor.preview();
  });

  window.noted = {};

}).call(this);
